services:
  - type: web
    name: mlb-gif-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manual_gif_dashboard.py
    healthCheckPath: /api/ping
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000 